# -*- coding: utf-8 -*-
"""manim_import_v2.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZsRPyLaUgWr6nvKfr6hDMoM9QPgyzsCq
"""

!apt-get update -qq
!apt-get install -y ffmpeg libcairo2-dev libpango1.0-dev texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science
!pip install manim gTTS

!pip install -q edge-tts

!edge-tts \
--voice el-GR-NestorasNeural \
--rate "+5%" \
--text "Σε αυτό το tutorial θα δούμε τη φθίνουσα μονοτονική στοίβα." \
--write-media /content/test_male.mp3

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/monotonic_stack.py
# from manim import *
# from pathlib import Path
# import json
# 
# 
# class MonotonicStackQ1Tutorial(Scene):
#     def construct(self):
#         self.camera.background_color = "#0f1117"
# 
#         plan_path = Path.cwd() / "tutorial_audio_build" / "narration_plan.json"
#         if plan_path.exists():
#             timings = json.loads(plan_path.read_text(encoding="utf-8"))
#         else:
#             timings = {}
# 
#         def voice_wait(key, default=1.5, used=0.0):
#             duration = float(timings.get(key, default))
#             remaining = duration - used
# 
#             if key not in timings:
#                 print(f"⚠️ Missing narration timing for key: {key}. Using default={default}")
# 
#             if remaining < 0:
#                 print(
#                     f"⚠️ Segment '{key}' may desync: "
#                     f"audio={duration:.2f}s, used animation={used:.2f}s"
#                 )
# 
#             self.wait(max(remaining, 0.15))
# 
#         title_color = BLUE_B
#         accent = YELLOW
#         good = GREEN_B
#         warn = ORANGE
#         bad = RED_B
#         text_color = GREY_A
# 
#         LEFT_ZONE_X = -3.45
#         CONTENT_Y = -0.2
#         STATUS_Y = -3.35
#         ALERT_Y = -2.55
# 
#         def shrink_to_width(mobj, max_width):
#             if mobj.width > max_width:
#                 mobj.scale(max_width / mobj.width)
#             return mobj
# 
#         def shrink_to_height(mobj, max_height):
#             if mobj.height > max_height:
#                 mobj.scale(max_height / mobj.height)
#             return mobj
# 
#         def place_left(mobj, max_width=5.35, y=CONTENT_Y):
#             shrink_to_width(mobj, max_width)
#             mobj.move_to([LEFT_ZONE_X, y, 0])
#             return mobj
# 
#         def place_bottom(mobj, max_width=11.0, y=STATUS_Y):
#             shrink_to_width(mobj, max_width)
#             mobj.move_to([0, y, 0])
#             return mobj
# 
#         def make_status(text, color=text_color, font_size=22):
#             status = Text(
#                 text,
#                 font="DejaVu Sans",
#                 font_size=font_size,
#                 color=color,
#             )
#             shrink_to_width(status, 11.0)
#             status.move_to([0, STATUS_Y, 0])
#             return status
# 
#         def make_alert(text, color=warn, font_size=24):
#             alert = Text(
#                 text,
#                 font="DejaVu Sans",
#                 font_size=font_size,
#                 color=color,
#             )
#             shrink_to_width(alert, 10.5)
#             alert.move_to([0, ALERT_Y, 0])
#             return alert
# 
#         def section_title(main_text, sub_text="", color=title_color):
#             main = Text(
#                 main_text,
#                 font="DejaVu Sans",
#                 weight=BOLD,
#                 font_size=42,
#                 color=color,
#             )
#             sub = Text(
#                 sub_text,
#                 font="DejaVu Sans",
#                 font_size=22,
#                 color=text_color,
#             )
#             group = VGroup(main, sub).arrange(DOWN, aligned_edge=LEFT, buff=0.16)
#             group.to_edge(UP)
#             shrink_to_width(group, 11.2)
#             return group
# 
#         def bullet_list(items, font_size=24, color=text_color, buff=0.26):
#             bullets = VGroup()
#             for item in items:
#                 line = Text(
#                     f"• {item}",
#                     font="DejaVu Sans",
#                     font_size=font_size,
#                     color=color,
#                 )
#                 shrink_to_width(line, 5.3)
#                 bullets.add(line)
#             bullets.arrange(DOWN, aligned_edge=LEFT, buff=buff)
#             return bullets
# 
#         def make_array_row(values, y=1.0):
#             cells = VGroup()
#             labels = VGroup()
# 
#             for i, v in enumerate(values):
#                 box = Square(side_length=0.78, color=GREY_B).set_stroke(width=2)
#                 box.move_to(LEFT * 2.8 + RIGHT * i * 0.88 + UP * y)
# 
#                 txt = Text(
#                     str(v),
#                     font="DejaVu Sans",
#                     font_size=26,
#                     color=WHITE,
#                 ).move_to(box.get_center())
# 
#                 idx = Text(
#                     str(i),
#                     font="DejaVu Sans",
#                     font_size=17,
#                     color=GREY_A,
#                 ).next_to(box, DOWN, buff=0.10)
# 
#                 cells.add(box)
#                 labels.add(VGroup(txt, idx))
# 
#             group = VGroup(cells, labels)
#             shrink_to_width(group, 5.8)
#             group.move_to([-2.45, 0.9, 0])
# 
#             return cells, labels
# 
#         def make_stack_group(stack_values, origin=RIGHT * 4.25 + DOWN * 1.1):
#             stack = VGroup()
# 
#             for i, val in enumerate(stack_values):
#                 rect = RoundedRectangle(
#                     corner_radius=0.08,
#                     width=1.38,
#                     height=0.56,
#                     color=good,
#                 ).set_fill(good, opacity=0.12)
# 
#                 rect.move_to(origin + UP * i * 0.66)
# 
#                 txt = Text(
#                     str(val),
#                     font="DejaVu Sans",
#                     font_size=22,
#                     color=WHITE,
#                 ).move_to(rect.get_center())
# 
#                 stack.add(VGroup(rect, txt))
# 
#             return stack
# 
#         def stack_frame(height=4.15):
#             frame = RoundedRectangle(
#                 corner_radius=0.12,
#                 width=1.85,
#                 height=height,
#                 color=GREY_B,
#             ).set_stroke(width=2)
# 
#             frame.move_to(RIGHT * 4.25 + DOWN * 0.2)
# 
#             label = Text(
#                 "Stack",
#                 font="DejaVu Sans",
#                 font_size=23,
#                 color=accent,
#             ).next_to(frame, UP, buff=0.18)
# 
#             top_label = Text(
#                 "top",
#                 font="DejaVu Sans",
#                 font_size=18,
#                 color=accent,
#             ).next_to(frame.get_top(), RIGHT, buff=0.12)
# 
#             return VGroup(frame, label, top_label)
# 
#         # =========================
#         # INTRO
#         # =========================
#         intro = VGroup(
#             Text(
#                 "Φθίνουσα Μονοτονική Στοίβα",
#                 font="DejaVu Sans",
#                 font_size=46,
#                 weight=BOLD,
#                 color=title_color,
#             ),
#             Text(
#                 "concept • pattern • trace • template • warnings",
#                 font="DejaVu Sans",
#                 font_size=24,
#                 color=text_color,
#             ),
#         ).arrange(DOWN, buff=0.25)
# 
#         shrink_to_width(intro, 11.2)
# 
#         self.play(FadeIn(intro, shift=UP), run_time=1.4)
#         voice_wait("intro", default=2.0, used=1.4)
#         self.play(FadeOut(intro), run_time=0.8)
# 
#         # =========================
#         # CONCEPT
#         # =========================
#         t1 = section_title(
#             "concept",
#             "Τι είναι η φθίνουσα μονοτονική στοίβα",
#         )
#         self.play(FadeIn(t1, shift=UP), run_time=0.8)
# 
#         concept_left = bullet_list(
#             [
#                 "Στοίβα όπου από κάτω προς τα πάνω οι τιμές μένουν σε φθίνουσα σειρά.",
#                 "Πριν βάλουμε νέο x, πετάμε από την κορυφή όσα χαλάνε τη φθίνουσα τάξη.",
#                 "Χρήσιμη για κοντινότερο μεγαλύτερο ή για να κρατάμε μόνο υποψήφιους.",
#             ],
#             font_size=23,
#         )
#         place_left(concept_left, max_width=5.25, y=-0.15)
# 
#         values = [9, 7, 5]
#         sf = stack_frame()
#         sg = make_stack_group(values)
# 
#         invariant_box = RoundedRectangle(
#             corner_radius=0.12,
#             width=5.0,
#             height=1.05,
#             color=accent,
#         ).set_fill(accent, opacity=0.08)
# 
#         invariant_box.move_to([-3.35, -2.35, 0])
# 
#         invariant_text = VGroup(
#             Text(
#                 "Invariant:",
#                 font="DejaVu Sans",
#                 font_size=24,
#                 color=accent,
#                 weight=BOLD,
#             ),
#             Text(
#                 "κάθε νέα κορυφή ≤ την προηγούμενη",
#                 font="DejaVu Sans",
#                 font_size=21,
#                 color=WHITE,
#             ),
#         ).arrange(DOWN, aligned_edge=LEFT, buff=0.08)
# 
#         shrink_to_width(invariant_text, 4.65)
#         invariant_text.move_to(invariant_box.get_center())
# 
#         self.play(
#             FadeIn(concept_left, shift=RIGHT),
#             Create(sf),
#             FadeIn(sg, shift=UP),
#             run_time=1.6,
#         )
#         self.play(FadeIn(invariant_box), Write(invariant_text), run_time=1.0)
#         voice_wait("concept_main", default=5.0, used=2.6)
# 
#         x_label = Text(
#             "Νέο στοιχείο: 6",
#             font="DejaVu Sans",
#             font_size=25,
#             color=accent,
#         )
#         x_label.move_to([1.35, 1.3, 0])
# 
#         x_box = Square(side_length=0.78, color=accent).set_fill(accent, opacity=0.1)
#         x_num = Text("6", font="DejaVu Sans", font_size=26, color=WHITE).move_to(x_box)
#         x_group = VGroup(x_box, x_num).next_to(x_label, DOWN, buff=0.22)
# 
#         pop_note = make_alert("6 > 5  →  pop")
# 
#         self.play(FadeIn(x_label), FadeIn(x_group), run_time=0.8)
#         self.play(
#             FadeIn(pop_note),
#             Indicate(sg[-1][0], color=warn),
#             run_time=1.0,
#         )
#         self.play(FadeOut(sg[-1], shift=UP), run_time=0.7)
# 
#         old_stack_without_top = make_stack_group([9, 7])
#         new_stack = make_stack_group([9, 7, 6])
# 
#         self.play(ReplacementTransform(sg[:-1], old_stack_without_top), run_time=0.5)
#         self.play(FadeIn(new_stack[-1], shift=UP), run_time=0.6)
#         self.play(FadeOut(pop_note), run_time=0.3)
#         voice_wait("concept_pop", default=3.5, used=3.9)
# 
#         self.play(
#             FadeOut(concept_left),
#             FadeOut(sf),
#             FadeOut(old_stack_without_top),
#             FadeOut(new_stack[-1]),
#             FadeOut(invariant_box),
#             FadeOut(invariant_text),
#             FadeOut(x_label),
#             FadeOut(x_group),
#             FadeOut(t1),
#             run_time=1.0,
#         )
# 
#         # =========================
#         # PATTERN
#         # =========================
#         t2 = section_title(
#             "pattern",
#             "Ποια είναι η γενική ροή",
#         )
#         self.play(FadeIn(t2, shift=UP), run_time=0.8)
# 
#         flow_box = RoundedRectangle(
#             corner_radius=0.15,
#             width=10.5,
#             height=4.5,
#             color=BLUE_D,
#         ).set_fill(BLUE_D, opacity=0.08)
# 
#         flow_box.shift(DOWN * 0.25)
# 
#         steps = VGroup(
#             Text(
#                 "1. Σαρώνω τον πίνακα από αριστερά προς τα δεξιά",
#                 font="DejaVu Sans",
#                 font_size=26,
#                 color=WHITE,
#             ),
#             Text(
#                 "2. Όσο η κορυφή παραβιάζει τον κανόνα, κάνω pop",
#                 font="DejaVu Sans",
#                 font_size=26,
#                 color=WHITE,
#             ),
#             Text(
#                 "3. Με ό,τι μένει στην κορυφή, βγάζω πληροφορία αν χρειάζεται",
#                 font="DejaVu Sans",
#                 font_size=25,
#                 color=WHITE,
#             ),
#             Text(
#                 "4. Βάζω το τρέχον στοιχείο στη στοίβα",
#                 font="DejaVu Sans",
#                 font_size=26,
#                 color=WHITE,
#             ),
#         ).arrange(DOWN, aligned_edge=LEFT, buff=0.38)
# 
#         shrink_to_width(steps, 9.6)
#         steps.move_to(flow_box.get_center())
# 
#         mini_hint = Text(
#             "Για φθίνουσα στοίβα: αφαιρώ μικρότερα ή ίσα, ανάλογα με το πρόβλημα.",
#             font="DejaVu Sans",
#             font_size=23,
#             color=accent,
#         )
#         place_bottom(mini_hint, y=STATUS_Y)
# 
#         self.play(Create(flow_box), run_time=0.8)
# 
#         for i, s in enumerate(steps, start=1):
#             self.play(Write(s), run_time=0.7)
#             voice_wait(f"pattern_step_{i}", default=1.4, used=0.7)
# 
#         self.play(FadeIn(mini_hint), run_time=0.7)
#         voice_wait("pattern_hint", default=5.0, used=0.7)
# 
#         self.play(
#             FadeOut(flow_box),
#             FadeOut(steps),
#             FadeOut(mini_hint),
#             FadeOut(t2),
#             run_time=0.9,
#         )
# 
#         # =========================
#         # TRACE
#         # =========================
#         t3 = section_title(
#             "trace",
#             "Πώς εξελίσσεται σε ένα παράδειγμα",
#         )
#         self.play(FadeIn(t3, shift=UP), run_time=0.8)
# 
#         arr = [7, 5, 6, 3, 4, 2]
#         cells, labels = make_array_row(arr, y=1.0)
#         sf2 = stack_frame()
# 
#         arr_title = Text(
#             "Παράδειγμα εισόδου",
#             font="DejaVu Sans",
#             font_size=23,
#             color=accent,
#         ).next_to(cells, UP, buff=0.22)
# 
#         self.play(
#             FadeIn(arr_title),
#             LaggedStart(*[Create(c) for c in cells], lag_ratio=0.08),
#             LaggedStart(*[FadeIn(l) for l in labels], lag_ratio=0.08),
#             Create(sf2),
#             run_time=1.4,
#         )
# 
#         current_marker = Triangle(color=accent, fill_opacity=1).scale(0.16).rotate(PI)
#         current_marker.next_to(cells[0], UP, buff=0.10)
# 
#         status = make_status("Ξεκινάμε με κενή στοίβα")
# 
#         stack_vals = []
#         stack_mobj = VGroup()
# 
#         self.play(FadeIn(current_marker), FadeIn(status), run_time=0.8)
# 
#         def redraw_stack():
#             return make_stack_group(stack_vals)
# 
#         self.play(Indicate(cells[0], color=accent), run_time=0.6)
# 
#         stack_vals.append(7)
#         new_stack = redraw_stack()
# 
#         self.play(FadeIn(new_stack, shift=UP), run_time=0.7)
#         stack_mobj = new_stack
# 
#         new_status = make_status("7 μπαίνει στη στοίβα")
#         self.play(Transform(status, new_status), run_time=0.6)
#         voice_wait("trace_7", default=2.8, used=1.9)
# 
#         self.play(
#             current_marker.animate.next_to(cells[1], UP, buff=0.10),
#             run_time=0.5,
#         )
#         self.play(Indicate(cells[1], color=accent), run_time=0.5)
# 
#         stack_vals.append(5)
#         new_stack = redraw_stack()
# 
#         self.play(ReplacementTransform(stack_mobj, new_stack), run_time=0.7)
#         stack_mobj = new_stack
# 
#         new_status = make_status(
#             "5 ≤ 7, άρα κρατάμε τη φθίνουσα σειρά και κάνουμε push"
#         )
#         self.play(Transform(status, new_status), run_time=0.7)
#         voice_wait("trace_5", default=2.5, used=2.4)
# 
#         self.play(
#             current_marker.animate.next_to(cells[2], UP, buff=0.10),
#             run_time=0.5,
#         )
#         self.play(Indicate(cells[2], color=accent), run_time=0.5)
# 
#         pop_text = make_alert("6 > 5, οπότε το 5 φεύγει")
# 
#         self.play(
#             FadeIn(pop_text),
#             Indicate(stack_mobj[-1][0], color=warn),
#             run_time=0.8,
#         )
# 
#         stack_vals.pop()
#         new_stack = redraw_stack()
# 
#         self.play(ReplacementTransform(stack_mobj, new_stack), run_time=0.7)
#         stack_mobj = new_stack
# 
#         stack_vals.append(6)
#         newer_stack = redraw_stack()
# 
#         self.play(ReplacementTransform(stack_mobj, newer_stack), run_time=0.7)
#         stack_mobj = newer_stack
# 
#         self.play(FadeOut(pop_text), run_time=0.3)
# 
#         new_status = make_status(
#             "Μετά το pop, το 6 μπαίνει και η στοίβα ξαναγίνεται φθίνουσα"
#         )
#         self.play(Transform(status, new_status), run_time=0.7)
#         voice_wait("trace_6", default=4.5, used=4.2)
# 
#         self.play(
#             current_marker.animate.next_to(cells[3], UP, buff=0.10),
#             run_time=0.5,
#         )
#         self.play(Indicate(cells[3], color=accent), run_time=0.5)
# 
#         stack_vals.append(3)
#         new_stack = redraw_stack()
# 
#         self.play(ReplacementTransform(stack_mobj, new_stack), run_time=0.7)
#         stack_mobj = new_stack
# 
#         new_status = make_status("3 ≤ 6, άρα απλώς μπαίνει πάνω από το 6")
#         self.play(Transform(status, new_status), run_time=0.6)
#         voice_wait("trace_3", default=2.2, used=1.8)
# 
#         self.play(
#             current_marker.animate.next_to(cells[4], UP, buff=0.10),
#             run_time=0.5,
#         )
#         self.play(Indicate(cells[4], color=accent), run_time=0.5)
# 
#         pop_text2 = make_alert("4 > 3, άρα το 3 βγαίνει")
# 
#         self.play(
#             FadeIn(pop_text2),
#             Indicate(stack_mobj[-1][0], color=warn),
#             run_time=0.8,
#         )
# 
#         stack_vals.pop()
#         new_stack = redraw_stack()
# 
#         self.play(ReplacementTransform(stack_mobj, new_stack), run_time=0.7)
#         stack_mobj = new_stack
# 
#         stack_vals.append(4)
#         newer_stack = redraw_stack()
# 
#         self.play(ReplacementTransform(stack_mobj, newer_stack), run_time=0.7)
#         stack_mobj = newer_stack
# 
#         self.play(FadeOut(pop_text2), run_time=0.3)
# 
#         new_status = make_status("Μετά το pop, το 4 μπαίνει πάνω από το 6")
#         self.play(Transform(status, new_status), run_time=0.7)
#         voice_wait("trace_4", default=4.0, used=4.2)
# 
#         self.play(
#             current_marker.animate.next_to(cells[5], UP, buff=0.10),
#             run_time=0.5,
#         )
#         self.play(Indicate(cells[5], color=accent), run_time=0.5)
# 
#         stack_vals.append(2)
#         new_stack = redraw_stack()
# 
#         self.play(ReplacementTransform(stack_mobj, new_stack), run_time=0.7)
#         stack_mobj = new_stack
# 
#         new_status = make_status("2 ≤ 4, άρα μπαίνει χωρίς pop")
#         self.play(Transform(status, new_status), run_time=0.7)
#         voice_wait("trace_2", default=2.0, used=1.9)
# 
#         summary_trace = Text(
#             "Τελική στοίβα: 7, 6, 4, 2 — πάντα φθίνουσα από κάτω προς τα πάνω",
#             font="DejaVu Sans",
#             font_size=23,
#             color=accent,
#         )
#         shrink_to_width(summary_trace, 10.5)
#         summary_trace.move_to([0, -2.65, 0])
# 
#         self.play(FadeIn(summary_trace), run_time=0.7)
#         voice_wait("trace_summary", default=4.0, used=0.7)
# 
#         self.play(
#             FadeOut(t3),
#             FadeOut(arr_title),
#             FadeOut(cells),
#             FadeOut(labels),
#             FadeOut(sf2),
#             FadeOut(stack_mobj),
#             FadeOut(current_marker),
#             FadeOut(status),
#             FadeOut(summary_trace),
#             run_time=1.0,
#         )
# 
#         # =========================
#         # TEMPLATE
#         # =========================
#         t4 = section_title(
#             "template",
#             "Ημιτελές skeleton — όχι πλήρης λύση συγκεκριμένου task",
#         )
#         self.play(FadeIn(t4, shift=UP), run_time=0.8)
# 
#         code_str = '''def solve(nums):
#     stack = []
#     ans = [None] * len(nums)   # ή άλλη δομή, ανάλογα με το task
# 
#     for i, x in enumerate(nums):
#         while stack and stack[-1] <= x:
#             # TODO:
#             # - pop()
#             # - ίσως ενημέρωση απάντησης / συσχέτιση index
#             stack.pop()
# 
#         # TODO:
#         # - διάβασε την κορυφή αν τη χρειάζεσαι
#         # - αποθήκευσε τιμή ή index, ανάλογα με το ζητούμενο
#         stack.append(x)
# 
#     return ans  # placeholder
# '''
# 
#         code = Code(
#             code_string=code_str,
#             tab_width=4,
#             language="Python",
#             background="window",
#             formatter_style="monokai",
#         )
# 
#         shrink_to_width(code, 10.8)
#         shrink_to_height(code, 5.05)
#         code.move_to([0, -0.25, 0])
# 
#         note = Text(
#             "Κράτα το μοτίβο, αλλά προσαρμόζεις τι αποθηκεύεις και πότε γράφεις απάντηση.",
#             font="DejaVu Sans",
#             font_size=23,
#             color=accent,
#         )
#         place_bottom(note, y=STATUS_Y)
# 
#         self.play(FadeIn(code), run_time=1.0)
#         self.play(FadeIn(note), run_time=0.8)
#         voice_wait("template", default=8.0, used=1.8)
# 
#         self.play(FadeOut(code), FadeOut(note), FadeOut(t4), run_time=1.0)
# 
#         # =========================
#         # WARNINGS
#         # =========================
#         t5 = section_title(
#             "warnings",
#             "Τι να προσέχω",
#         )
#         self.play(FadeIn(t5, shift=UP), run_time=0.8)
# 
#         warn_box = RoundedRectangle(
#             corner_radius=0.15,
#             width=11.0,
#             height=4.55,
#             color=bad,
#         ).set_fill(bad, opacity=0.06)
# 
#         warn_box.shift(DOWN * 0.18)
# 
#         warns = VGroup(
#             Text(
#                 "1. Τι βάζεις στη στοίβα; τιμές ή indices;",
#                 font="DejaVu Sans",
#                 font_size=26,
#                 color=WHITE,
#             ),
#             Text(
#                 "2. Αν έχεις ίσα στοιχεία, θες < ή <= στο while;",
#                 font="DejaVu Sans",
#                 font_size=26,
#                 color=WHITE,
#             ),
#             Text(
#                 "3. Η απάντηση γράφεται πριν ή μετά το push;",
#                 font="DejaVu Sans",
#                 font_size=26,
#                 color=WHITE,
#             ),
#             Text(
#                 "4. Ό,τι μπει βγαίνει το πολύ μία φορά → συνολικά O(n).",
#                 font="DejaVu Sans",
#                 font_size=26,
#                 color=WHITE,
#             ),
#         ).arrange(DOWN, aligned_edge=LEFT, buff=0.40)
# 
#         shrink_to_width(warns, 10.0)
#         warns.move_to(warn_box.get_center())
# 
#         final_line = Text(
#             "Στόχος: να αναγνωρίζεις το pattern, όχι να απομνημονεύεις έτοιμη λύση.",
#             font="DejaVu Sans",
#             font_size=24,
#             color=accent,
#         )
#         place_bottom(final_line, y=STATUS_Y)
# 
#         self.play(Create(warn_box), run_time=0.8)
# 
#         for i, w in enumerate(warns, start=1):
#             self.play(Write(w), run_time=0.7)
#             voice_wait(f"warning_{i}", default=1.2, used=0.7)
# 
#         self.play(FadeIn(final_line), run_time=0.8)
#         voice_wait("final_goal", default=5.0, used=0.8)
# 
#         self.play(
#             FadeOut(warn_box),
#             FadeOut(warns),
#             FadeOut(final_line),
#             FadeOut(t5),
#             run_time=1.0,
#         )
# 
#         # =========================
#         # OUTRO
#         # =========================
#         outro = VGroup(
#             Text(
#                 "Φθίνουσα Μονοτονική Στοίβα",
#                 font="DejaVu Sans",
#                 font_size=42,
#                 weight=BOLD,
#                 color=title_color,
#             ),
#             Text(
#                 "Concept → Pattern → Trace → Template → Warnings",
#                 font="DejaVu Sans",
#                 font_size=24,
#                 color=text_color,
#             ),
#         ).arrange(DOWN, buff=0.25)
# 
#         shrink_to_width(outro, 11.2)
# 
#         self.play(FadeIn(outro, shift=UP), run_time=1.0)
#         voice_wait("outro", default=3.0, used=1.0)
#         self.play(FadeOut(outro), run_time=0.8)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/build_talking_tutorial.py
# from pathlib import Path
# import subprocess
# import shutil
# import json
# import sys
# 
# # =========================
# # CONFIG
# # =========================
# ROOT = Path.cwd()
# 
# MANIM_FILE = ROOT / "monotonic_stack.py"
# SCENE_NAME = "MonotonicStackQ1Tutorial"
# 
# WORKDIR = ROOT / "tutorial_audio_build"
# WORKDIR.mkdir(exist_ok=True)
# 
# SEGMENTS_DIR = WORKDIR / "narration_segments"
# SEGMENTS_DIR.mkdir(parents=True, exist_ok=True)
# 
# NARRATION_PLAN_JSON = WORKDIR / "narration_plan.json"
# NARRATION_CONCAT_LIST = WORKDIR / "narration_concat.txt"
# NARRATION_MP3 = WORKDIR / "narration.mp3"
# NARRATION_WAV = WORKDIR / "narration.wav"
# 
# TUTORIAL_COPY = WORKDIR / "tutorial_synced_video_only.mp4"
# 
# # Τελικό σωστό αρχείο
# FINAL_VIDEO = WORKDIR / "final_fixed_fast.mp4"
# 
# # Αν αλλάξεις φωνή, ταχύτητα ή κείμενα, βάλε True.
# REGENERATE_TTS = True
# 
# # Αν έχεις ήδη έτοιμο Manim video και δεν άλλαξες το monotonic_stack.py, άστο True.
# # Αν άλλαξες το monotonic_stack.py, βάλε False για να ξαναγίνει render.
# USE_EXISTING_MANIM_VIDEO = True
# 
# # =========================
# # EDGE TTS CONFIG
# # =========================
# 
# # Αντρική ελληνική φωνή
# EDGE_VOICE = "el-GR-NestorasNeural"
# 
# # Ταχύτητα ομιλίας
# # "+0%"  = κανονική
# # "+5%"  = λίγο πιο γρήγορη
# # "+10%" = αρκετά πιο γρήγορη
# # "-5%"  = λίγο πιο αργή
# EDGE_RATE = "+5%"
# 
# # =========================
# # ΤΜΗΜΑΤΑ ΑΦΗΓΗΣΗΣ
# # Κάθε key αντιστοιχεί σε voice_wait(...) μέσα στο monotonic_stack.py
# # =========================
# NARRATION_SEGMENTS = [
#     {
#         "key": "intro",
#         "text": "Σε αυτό το tutorial θα δούμε τη φθίνουσα μονοτονική στοίβα. Ο στόχος δεν είναι να πάρεις έτοιμη πλήρη λύση, αλλά να καταλάβεις πώς σκέφτεσαι αυτό το pattern.",
#     },
#     {
#         "key": "concept_main",
#         "text": "Η φθίνουσα μονοτονική στοίβα κρατά στοιχεία έτσι ώστε από κάτω προς τα πάνω οι τιμές να μένουν σε φθίνουσα σειρά. Πριν βάλουμε ένα νέο στοιχείο, αφαιρούμε από την κορυφή όσα χαλάνε αυτόν τον κανόνα. Αυτό είναι χρήσιμο όταν ψάχνουμε κοντινότερο μεγαλύτερο στοιχείο ή όταν θέλουμε να κρατάμε μόνο υποψήφιους που παραμένουν χρήσιμοι.",
#     },
#     {
#         "key": "concept_pop",
#         "text": "Αν έρθει το έξι ενώ στην κορυφή υπάρχει το πέντε, τότε το έξι είναι μεγαλύτερο από το πέντε. Άρα το πέντε φεύγει με pop. Μετά το έξι μπορεί να μπει και η στοίβα ξαναγίνεται φθίνουσα.",
#     },
#     {
#         "key": "pattern_step_1",
#         "text": "Πρώτο βήμα. Σαρώνω τον πίνακα από αριστερά προς τα δεξιά, εκτός αν η άσκηση ζητά κάτι που βολεύει ανάποδη σάρωση.",
#     },
#     {
#         "key": "pattern_step_2",
#         "text": "Δεύτερο βήμα. Όσο η κορυφή της στοίβας παραβιάζει τον κανόνα, κάνω pop.",
#     },
#     {
#         "key": "pattern_step_3",
#         "text": "Τρίτο βήμα. Με ό,τι μένει στην κορυφή, βγάζω πληροφορία αν τη χρειάζομαι για την απάντηση.",
#     },
#     {
#         "key": "pattern_step_4",
#         "text": "Τέταρτο βήμα. Βάζω το τρέχον στοιχείο στη στοίβα, είτε ως τιμή είτε ως δείκτη.",
#     },
#     {
#         "key": "pattern_hint",
#         "text": "Για φθίνουσα στοίβα συνήθως αφαιρώ μικρότερα στοιχεία. Το αν θα αφαιρέσω και ίσα στοιχεία εξαρτάται από την εκφώνηση. Δηλαδή πρέπει να αποφασίσω αν στο while θα βάλω μικρότερο ή μικρότερο ίσο.",
#     },
#     {
#         "key": "trace_7",
#         "text": "Ας δούμε τώρα ένα παράδειγμα με είσοδο επτά, πέντε, έξι, τρία, τέσσερα, δύο. Πρώτα βλέπουμε το επτά. Η στοίβα είναι κενή, άρα το επτά μπαίνει.",
#     },
#     {
#         "key": "trace_5",
#         "text": "Μετά βλέπουμε το πέντε. Το πέντε είναι μικρότερο από το επτά, οπότε δεν χαλάει τη φθίνουσα σειρά και μπαίνει και αυτό στη στοίβα.",
#     },
#     {
#         "key": "trace_6",
#         "text": "Τώρα βλέπουμε το έξι. Η κορυφή είναι το πέντε. Επειδή το έξι είναι μεγαλύτερο από το πέντε, το πέντε δεν παραμένει χρήσιμο και αφαιρείται. Μετά το pop, το έξι μπαίνει και η στοίβα ξαναγίνεται φθίνουσα.",
#     },
#     {
#         "key": "trace_3",
#         "text": "Μετά βλέπουμε το τρία. Είναι μικρότερο ή ίσο από το έξι, οπότε μπαίνει χωρίς pop.",
#     },
#     {
#         "key": "trace_4",
#         "text": "Στη συνέχεια βλέπουμε το τέσσερα. Η κορυφή είναι το τρία. Επειδή το τέσσερα είναι μεγαλύτερο από το τρία, το τρία αφαιρείται. Έπειτα το τέσσερα μπαίνει πάνω από το έξι.",
#     },
#     {
#         "key": "trace_2",
#         "text": "Τέλος βλέπουμε το δύο. Το δύο είναι μικρότερο ή ίσο από το τέσσερα, άρα μπαίνει χωρίς pop.",
#     },
#     {
#         "key": "trace_summary",
#         "text": "Στο τέλος η στοίβα είναι επτά, έξι, τέσσερα, δύο. Παρατήρησε ότι δεν κρατά όλα τα στοιχεία της εισόδου. Κρατά μόνο όσα δεν αφαιρέθηκαν από κάποιο μεταγενέστερο στοιχείο.",
#     },
#     {
#         "key": "template",
#         "text": "Το template είναι επίτηδες ημιτελές. Κράτα το μοτίβο, αλλά προσαρμόζεις τι αποθηκεύεις και πότε γράφεις απάντηση. Αν χρειάζεσαι θέση, απόσταση ή αποτέλεσμα για συγκεκριμένο στοιχείο, συνήθως κρατάς δείκτες αντί για απλές τιμές.",
#     },
#     {
#         "key": "warning_1",
#         "text": "Πρώτη προσοχή. Τι βάζεις στη στοίβα; Τιμές ή indices; Η επιλογή αλλάζει τον τρόπο που γράφεις την απάντηση.",
#     },
#     {
#         "key": "warning_2",
#         "text": "Δεύτερη προσοχή. Αν έχεις ίσα στοιχεία, θες μικρότερο ή μικρότερο ίσο στο while; Η σωστή επιλογή εξαρτάται από το ζητούμενο.",
#     },
#     {
#         "key": "warning_3",
#         "text": "Τρίτη προσοχή. Η απάντηση γράφεται πριν το push, μετά το push, ή τη στιγμή που γίνεται pop; Δεν είναι ίδιο σε όλες τις ασκήσεις.",
#     },
#     {
#         "key": "warning_4",
#         "text": "Τέταρτη προσοχή. Παρότι υπάρχει while μέσα σε for, κάθε στοιχείο μπαίνει στη στοίβα το πολύ μία φορά και βγαίνει το πολύ μία φορά. Άρα συνολικά η πολυπλοκότητα είναι O του n.",
#     },
#     {
#         "key": "final_goal",
#         "text": "Ο στόχος είναι να αναγνωρίζεις το pattern και να το προσαρμόζεις στην εκφώνηση, όχι να απομνημονεύεις ένα έτοιμο template.",
#     },
#     {
#         "key": "outro",
#         "text": "Αυτό ήταν το βασικό μοτίβο της φθίνουσας μονοτονικής στοίβας: concept, pattern, trace, template και warnings.",
#     },
# ]
# 
# 
# # =========================
# # HELPERS
# # =========================
# def run(cmd, cwd=None):
#     printable = " ".join(str(x) for x in cmd)
#     print(f"\n>>> {printable}\n", flush=True)
#     subprocess.run(cmd, cwd=cwd, check=True)
# 
# 
# def require_file(path: Path, label: str):
#     if not path.exists():
#         raise FileNotFoundError(
#             f"Δεν βρέθηκε το {label}: {path}\n"
#             f"Βεβαιώσου ότι το αρχείο υπάρχει."
#         )
# 
# 
# def get_duration(path: Path) -> float:
#     require_file(path, f"αρχείο για duration ({path.name})")
# 
#     result = subprocess.run(
#         [
#             "ffprobe",
#             "-v", "error",
#             "-show_entries", "format=duration",
#             "-of", "default=noprint_wrappers=1:nokey=1",
#             str(path),
#         ],
#         capture_output=True,
#         text=True,
#         check=True,
#     )
# 
#     output = result.stdout.strip()
#     if not output:
#         raise RuntimeError(f"Το ffprobe δεν επέστρεψε διάρκεια για το αρχείο: {path}")
# 
#     return float(output)
# 
# 
# def find_latest_file(pattern: str):
#     files = list(ROOT.glob(pattern))
#     if not files:
#         return None
# 
#     files.sort(key=lambda p: p.stat().st_mtime)
#     return files[-1]
# 
# 
# def generate_edge_tts(text: str, output_path: Path):
#     run([
#         "edge-tts",
#         "--voice", EDGE_VOICE,
#         "--rate", EDGE_RATE,
#         "--text", text,
#         "--write-media", str(output_path),
#     ])
# 
# 
# # =========================
# # STEP 1: TTS AUDIO + PLAN
# # =========================
# def generate_tts_segments():
#     print("Δημιουργία τμηματικού TTS με edge-tts...")
#     print(f"Φωνή: {EDGE_VOICE}")
#     print(f"Ταχύτητα: {EDGE_RATE}")
# 
#     segment_files = []
#     timings = {}
# 
#     for index, item in enumerate(NARRATION_SEGMENTS, start=1):
#         key = item["key"]
#         text = item["text"].strip()
#         mp3_path = SEGMENTS_DIR / f"{index:03d}_{key}.mp3"
# 
#         if REGENERATE_TTS and mp3_path.exists():
#             mp3_path.unlink()
# 
#         if not mp3_path.exists():
#             print(f"TTS segment {index:03d}: {key}")
#             generate_edge_tts(text, mp3_path)
#         else:
#             print(f"Υπάρχει ήδη segment {index:03d}: {key}")
# 
#         duration = get_duration(mp3_path)
#         timings[key] = duration
#         segment_files.append(mp3_path)
# 
#     NARRATION_PLAN_JSON.write_text(
#         json.dumps(timings, ensure_ascii=False, indent=2),
#         encoding="utf-8",
#     )
# 
#     NARRATION_CONCAT_LIST.write_text(
#         "\n".join(f"file '{p.resolve().as_posix()}'" for p in segment_files),
#         encoding="utf-8",
#     )
# 
#     run([
#         "ffmpeg", "-y",
#         "-f", "concat",
#         "-safe", "0",
#         "-i", str(NARRATION_CONCAT_LIST),
#         "-ar", "44100",
#         "-ac", "2",
#         "-b:a", "192k",
#         str(NARRATION_MP3),
#     ])
# 
#     run([
#         "ffmpeg", "-y",
#         "-i", str(NARRATION_MP3),
#         "-ar", "44100",
#         "-ac", "2",
#         str(NARRATION_WAV),
#     ])
# 
#     print(f"Narration plan: {NARRATION_PLAN_JSON}")
#     print(f"Narration mp3: {NARRATION_MP3}")
#     print(f"Narration wav: {NARRATION_WAV}")
# 
#     return NARRATION_WAV
# 
# 
# # =========================
# # STEP 2: RENDER MANIM
# # =========================
# def render_tutorial():
#     require_file(MANIM_FILE, "monotonic_stack.py")
#     require_file(NARRATION_PLAN_JSON, "narration_plan.json")
# 
#     existing_video = ROOT / "media/videos/monotonic_stack/480p15/MonotonicStackQ1Tutorial.mp4"
# 
#     if USE_EXISTING_MANIM_VIDEO and existing_video.exists():
#         shutil.copy2(existing_video, TUTORIAL_COPY)
#         print(f"Χρησιμοποιώ ήδη υπάρχον Manim video: {existing_video}")
#         print(f"Tutorial video only: {TUTORIAL_COPY}")
#         return TUTORIAL_COPY
# 
#     run([
#         "manim",
#         "-ql",
#         "--disable_caching",
#         "--progress_bar", "display",
#         str(MANIM_FILE),
#         SCENE_NAME,
#     ])
# 
#     tutorial = find_latest_file("media/videos/**/MonotonicStackQ1Tutorial.mp4")
# 
#     if tutorial is None:
#         raise FileNotFoundError(
#             "Δεν βρέθηκε το tutorial mp4 μέσα στο media/videos.\n"
#             "Έλεγξε αν το Manim ολοκλήρωσε το render ή αν το scene name είναι σωστό."
#         )
# 
#     shutil.copy2(tutorial, TUTORIAL_COPY)
#     print(f"Tutorial video only: {TUTORIAL_COPY}")
# 
#     return TUTORIAL_COPY
# 
# 
# # =========================
# # STEP 3: ADD AUDIO TO VIDEO
# # =========================
# def add_audio_to_tutorial(tutorial_video: Path, narration_audio: Path):
#     video_duration = get_duration(tutorial_video)
#     audio_duration = get_duration(narration_audio)
# 
#     print(f"Διάρκεια Manim video: {video_duration:.2f}s")
#     print(f"Διάρκεια narration audio: {audio_duration:.2f}s")
# 
#     final_duration = max(video_duration, audio_duration)
# 
#     print(f"Τελική διάρκεια στόχος: {final_duration:.2f}s")
# 
#     run([
#         "ffmpeg", "-y",
#         "-i", str(tutorial_video),
#         "-i", str(narration_audio),
#         "-map", "0:v:0",
#         "-map", "1:a:0",
#         "-c:v", "copy",
#         "-c:a", "aac",
#         "-b:a", "192k",
#         "-af", "apad",
#         "-t", f"{final_duration:.2f}",
#         "-movflags", "+faststart",
#         str(FINAL_VIDEO),
#     ])
# 
#     checked_duration = get_duration(FINAL_VIDEO)
# 
#     print(f"\n✅ Τελικό video με αντρική φωνή: {FINAL_VIDEO}")
#     print(f"✅ Τελική διάρκεια: {checked_duration:.2f}s\n")
# 
#     return FINAL_VIDEO
# 
# 
# # =========================
# # MAIN
# # =========================
# def main():
#     narration_audio = generate_tts_segments()
#     tutorial_video = render_tutorial()
#     add_audio_to_tutorial(tutorial_video, narration_audio)
# 
# 
# if __name__ == "__main__":
#     try:
#         main()
#     except Exception as e:
#         print("\n❌ Σφάλμα build:")
#         print(e)
#         sys.exit(1)

!python /content/build_talking_tutorial.py

!ls -lah /content/tutorial_audio_build

!ffmpeg -y \
-i /content/tutorial_audio_build/tutorial_synced_video_only.mp4 \
-i /content/tutorial_audio_build/narration.wav \
-map 0:v:0 \
-map 1:a:0 \
-c:v copy \
-c:a aac \
-b:a 192k \
-af apad \
-t 264.27 \
-movflags +faststart \
/content/tutorial_audio_build/final_fixed_fast.mp4

!ffprobe -hide_banner /content/tutorial_audio_build/final_fixed_fast.mp4

!ls -lh /content/media/videos/monotonic_stack/480p15/partial_movie_files/MonotonicStackQ1Tutorial

from IPython.display import Video, display

display(Video("/content/tutorial_audio_build/final_fixed_fast.mp4", embed=True))